### ISSUE TITLE
Breaking with typescript version 3.7.2

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode-typescript-tslint-plugin#124]
Follows on from https://github.com/microsoft/vscode/issues/85999

Using workspace version TS 3.7.2 just breaks the plugin completely, it fails to work at all.

@mjbvz bump, edited issue desc and title

**Comment by jpike88** [comment]
https://github.com/microsoft/vscode/issues/85999

**Comment by jpike88** [comment]
error in log:

```
Err 35    [11:21:8.644] Exception on executing command {"seq":9,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts","line":520,"offset":29}}:

    Could not find source file: '/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts'.

    Error: Could not find source file: '/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts'.
        at getValidSourceFile (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:130492:29)
        at Object.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:130813:73)
        at Proxy.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:71029:35)
        at IOSession.Session.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139891:83)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139249:61)
        at /Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140870:88
        at IOSession.Session.executeWithRequestId (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140861:28)
        at IOSession.Session.executeCommand (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140870:33)
        at IOSession.Session.onMessage (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140893:35)
        at Interface.<anonymous> (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:142208:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

Could not find source file is a weird error, that path DEFINITELY exists.

**Comment by mjbvz** [comment]
Can you please also test with 3.7.3 which was just released. 

Also were you able to put together a small project that demonstrates this? I still haven't been able to reproduce the problem

**Comment by mjbvz** [comment]
Closing this as not actionable without an example project and steps to reproduce
