### ISSUE TITLE
How to lint entire project

### ISSUE THREAD

**Issue by jasonswearingen** [Microsoft/vscode-typescript-tslint-plugin#69]
I can not figure out how to get the entire project linted.

opening a file lints properly, but closed files do not get linted (when the project gets rebuilt)

I have all the needed modules installed (i tried installing ```typescript tslint typescript-tslint-plugin``` as both local and global modules, this doesn't work)

in #20 they "solved" the problem by just running tslint manually as a task, which is not actually solving the problem.

I am using:
- ts v3.3.3333
- vscode v1.31.1
  - tslint plugin v1.0.0 (vscode-typescript-tslint-plugin)
- npm packages:
  - tslint@5.13.1
  - typescript@3.3.3333
  - typescript-tslint-plugin@0.3.1

I tried enabling ts server logs (```"typescript.tsserver.log": "verbose",```) as per this comment: https://github.com/Microsoft/vscode-typescript-tslint-plugin/issues/41#issuecomment-457006868  but In VSCode's command pallete I don't have any option similar to ```TypeScript: Open TS Server log```.

**Comment by jasonswearingen** [comment]
I found what appears to be the TSServer logs in the ```Output.log.window``` section of the vscode editor.

<details>
<summary>log window output</summary>

[2019-03-10 11:09:36.190] [renderer1] [info] no standard startup: not just one text editor
[2019-03-10 11:12:28.546] [renderer1] [error] TypeScript Server Error (3.3.1)
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (tsserver.js:1494:24)
    at deleteNodeInList (tsserver.js:109523:43)
    at Object.deleteDeclaration (tsserver.js:109442:29)
    at _loop_9 (tsserver.js:109026:47)
    at ChangeTracker.finishDeleteDeclarations (tsserver.js:109033:21)
    at ChangeTracker.getChanges (tsserver.js:109053:22)
    at Function.ChangeTracker.with (tsserver.js:108598:32)
    at Object.getCodeActions (tsserver.js:113243:69)
    at tsserver.js:109583:121
    at Object.flatMap (tsserver.js:504:25)
    at Object.getFixes (tsserver.js:109583:23)
    at tsserver.js:118787:35
    at Object.flatMap (tsserver.js:504:25)
    at Object.getCodeFixesAtPosition (tsserver.js:118785:23)
    at TSLintPlugin.getCodeFixesAtPosition (C:\Users\jason\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0\node_modules\typescript-tslint-plugin\out\plugin.js:143:34)
    at Proxy.intercept.getCodeFixesAtPosition.args (C:\Users\jason\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0\node_modules\typescript-tslint-plugin\out\plugin.js:75:25)
    at IOSession.Session.getCodeFixes (tsserver.js:126938:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125743:61)
    at tsserver.js:127107:88
    at IOSession.Session.executeWithRequestId (tsserver.js:127098:28)
    at IOSession.Session.executeCommand (tsserver.js:127107:33)
    at IOSession.Session.onMessage (tsserver.js:127129:35)
    at Interface.<anonymous> (tsserver.js:128390:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20): Error: TypeScript Server Error (3.3.1)
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (tsserver.js:1494:24)
    at deleteNodeInList (tsserver.js:109523:43)
    at Object.deleteDeclaration (tsserver.js:109442:29)
    at _loop_9 (tsserver.js:109026:47)
    at ChangeTracker.finishDeleteDeclarations (tsserver.js:109033:21)
    at ChangeTracker.getChanges (tsserver.js:109053:22)
    at Function.ChangeTracker.with (tsserver.js:108598:32)
    at Object.getCodeActions (tsserver.js:113243:69)
    at tsserver.js:109583:121
    at Object.flatMap (tsserver.js:504:25)
    at Object.getFixes (tsserver.js:109583:23)
    at tsserver.js:118787:35
    at Object.flatMap (tsserver.js:504:25)
    at Object.getCodeFixesAtPosition (tsserver.js:118785:23)
    at TSLintPlugin.getCodeFixesAtPosition (C:\Users\jason\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0\node_modules\typescript-tslint-plugin\out\plugin.js:143:34)
    at Proxy.intercept.getCodeFixesAtPosition.args (C:\Users\jason\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0\node_modules\typescript-tslint-plugin\out\plugin.js:75:25)
    at IOSession.Session.getCodeFixes (tsserver.js:126938:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125743:61)
    at tsserver.js:127107:88
    at IOSession.Session.executeWithRequestId (tsserver.js:127098:28)
    at IOSession.Session.executeCommand (tsserver.js:127107:33)
    at IOSession.Session.onMessage (tsserver.js:127129:35)
    at Interface.<anonymous> (tsserver.js:128390:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at v.dispatchResponse (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:178116)
	at v.dispatchMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:176870)
	at constructor._reader.onData.e (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:176226)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at t.Reader.onLengthData (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:182299)
	at Socket.t.Reader.constructor.e.on.e (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:181947)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-10 11:12:36.223] [renderer1] [error] Tree element not found: {
	"resource": "/f:/repos/stage5/xlib/src/_unit.test.ts",
	"owner": "typescript",
	"code": "1",
	"severity": 4,
	"message": "Shadowed name: 'log' (no-shadowed-variable)",
	"source": "tslint",
	"startLineNumber": 62,
	"startColumn": 9,
	"endLineNumber": 62,
	"endColumn": 12
}: Error: Tree element not found: {
	"resource": "/f:/repos/stage5/xlib/src/_unit.test.ts",
	"owner": "typescript",
	"code": "1",
	"severity": 4,
	"message": "Shadowed name: 'log' (no-shadowed-variable)",
	"source": "tslint",
	"startLineNumber": 62,
	"startColumn": 9,
	"endLineNumber": 62,
	"endColumn": 12
}
    at e.getElementLocation (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:985)
    at e.getListIndex (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:12)
    at i.e.reveal (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1019:586)
    at t.revealMarkersForCurrentActiveEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4900:332)
    at t.autoReveal (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4900:95)
    at t.onActiveEditorChanged (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4897:212)
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:332)
    at t.doEmitActiveEditorChangeEvent (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4911:709)
    at t.handleActiveEditorChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4911:485)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4911:833
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:312)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5348:314
[2019-03-10 11:27:25.947] [renderer1] [error] Tree element not found: {
	"resource": "/f:/repos/stage5/xlib/src/_unit.test.ts",
	"owner": "typescript",
	"code": "1",
	"severity": 4,
	"message": "for (... in ...) statements must be filtered with an if statement (forin)",
	"source": "tslint",
	"startLineNumber": 392,
	"startColumn": 4,
	"endLineNumber": 412,
	"endColumn": 5
}: Error: Tree element not found: {
	"resource": "/f:/repos/stage5/xlib/src/_unit.test.ts",
	"owner": "typescript",
	"code": "1",
	"severity": 4,
	"message": "for (... in ...) statements must be filtered with an if statement (forin)",
	"source": "tslint",
	"startLineNumber": 392,
	"startColumn": 4,
	"endLineNumber": 412,
	"endColumn": 5
}
    at e.getElementLocation (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:985)
    at e.getNode (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:628)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1018:286
    at Array.map (<anonymous>)
    at i.e.setSelection (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1018:255)
    at t.onFocus (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2410:277)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2410:105
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:83:730
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:83:899
    at Array.forEach (<anonymous>)
    at e.bufferEvents (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:83:872)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1012:251
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:312)
    at e.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:90:602)
    at e.setChildren (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:97:769)
    at i.t.setChildren (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1024:345)
    at t.refreshPanel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4891:34)
    at t.onDidChangeModel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4896:754)
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:332)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:77:14
[2019-03-10 11:28:46.868] [renderer1] [error] Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:21482).: Error: Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:21482).
    at t.handleErrorResponse (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2789:701)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2789:133
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-03-10 11:33:28.532] [renderer1] [info] no standard startup: not a new window
[2019-03-10 11:35:06.120] [renderer1] [info] Requested uninstalling the extension eg2.tslint from window 1
[2019-03-10 11:47:50.236] [renderer1] [info] no standard startup: not a new window
[2019-03-10 11:51:23.200] [renderer1] [info] no standard startup: not a new window
[2019-03-10 11:59:18.965] [renderer1] [error] Illegal value for `line`: Error: Illegal value for `line`
	at t._lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:364:537)
	at Object.lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:363:320)
	at BlockHL.freeCurrentLine (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:152:42)
	at BHLController._onChangeText (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:240:23)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:133)
	at e.$acceptModelChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:524:279)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:744)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:322)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:155)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-10 11:59:18.969] [renderer1] [error] Illegal value for `line`: Error: Illegal value for `line`
	at t._lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:364:537)
	at Object.lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:363:320)
	at BlockHL.freeCurrentLine (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:152:42)
	at BHLController._onChangeText (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:240:23)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:133)
	at e.$acceptDirtyStateChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:524:48)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:744)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:322)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:155)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-10 12:04:44.796] [renderer1] [error] Tree element not found: {
	"resource": "/f:/repos/stage5/xlib/src/core/_diagnostics/logging.ts",
	"owner": "tslint-task",
	"severity": 8,
	"message": "Multiple imports from '../environment' can be combined into one.",
	"source": "tslint",
	"startLineNumber": 12,
	"startColumn": 1,
	"endLineNumber": 12,
	"endColumn": 1
}: Error: Tree element not found: {
	"resource": "/f:/repos/stage5/xlib/src/core/_diagnostics/logging.ts",
	"owner": "tslint-task",
	"severity": 8,
	"message": "Multiple imports from '../environment' can be combined into one.",
	"source": "tslint",
	"startLineNumber": 12,
	"startColumn": 1,
	"endLineNumber": 12,
	"endColumn": 1
}
    at e.getElementLocation (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:985)
    at e.getListIndex (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:12)
    at i.e.reveal (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1019:586)
    at t.revealMarkersForCurrentActiveEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4900:332)
    at t.autoReveal (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4900:95)
    at t.onActiveEditorChanged (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4897:212)
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:332)
    at t.doEmitActiveEditorChangeEvent (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4911:709)
    at t.handleActiveEditorChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4911:485)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4911:833
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:312)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5348:314
[2019-03-10 12:07:43.411] [renderer1] [error] Tree element not found: {
	"resource": "/f:/repos/stage5/xlib/src/core/_diagnostics/logging.ts",
	"owner": "tslint-task",
	"severity": 8,
	"message": "Multiple imports from '../environment' can be combined into one.",
	"source": "tslint",
	"startLineNumber": 12,
	"startColumn": 1,
	"endLineNumber": 12,
	"endColumn": 1
}: Error: Tree element not found: {
	"resource": "/f:/repos/stage5/xlib/src/core/_diagnostics/logging.ts",
	"owner": "tslint-task",
	"severity": 8,
	"message": "Multiple imports from '../environment' can be combined into one.",
	"source": "tslint",
	"startLineNumber": 12,
	"startColumn": 1,
	"endLineNumber": 12,
	"endColumn": 1
}
    at e.getElementLocation (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:985)
    at e.getNode (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:628)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1018:286
    at Array.map (<anonymous>)
    at i.e.setSelection (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1018:255)
    at t.onFocus (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2410:277)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2410:105
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:83:730
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:83:899
    at Array.forEach (<anonymous>)
    at e.bufferEvents (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:83:872)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1012:251
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:312)
    at e.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:90:602)
    at e.setChildren (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:97:769)
    at i.t.setChildren (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1024:345)
    at t.refreshPanel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4891:34)
    at t.onDidChangeModel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4896:754)
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:332)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:77:14
[2019-03-10 12:40:25.316] [renderer1] [info] no standard startup: not a new window
[2019-03-10 12:47:51.036] [renderer1] [error] Illegal value for `line`: Error: Illegal value for `line`
	at t._lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:364:537)
	at Object.lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:363:320)
	at BlockHL.findBot (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:109:36)
	at BlockHL.updateLine (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:45:32)
	at BHLController._onLineChange (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:246:23)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:133)
	at e.$acceptEditorPropertiesChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:678)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:744)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:322)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:155)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-10 12:48:27.979] [renderer1] [info] no standard startup: not a new window
[2019-03-10 12:55:25.091] [renderer1] [error] write EPIPE: Error: write EPIPE
	at afterWriteDispatched (internal/stream_base_commons.js:75:25)
	at writeGeneric (internal/stream_base_commons.js:70:3)
	at Socket._writeGeneric (net.js:758:5)
	at Socket._write (net.js:770:8)
	at doWrite (_stream_writable.js:410:12)
	at clearBuffer (_stream_writable.js:540:7)
	at onwrite (_stream_writable.js:465:7)
	at WriteWrap.afterWrite [as oncomplete] (net.js:845:19)
[2019-03-10 12:56:41.618] [renderer1] [info] no standard startup: not a new window
[2019-03-10 12:57:57.196] [renderer1] [info] no standard startup: not a new window
[2019-03-10 13:12:26.769] [renderer1] [info] no standard startup: not a new window
[2019-03-10 13:14:26.057] [renderer1] [info] no standard startup: not a new window
[2019-03-10 13:15:12.902] [renderer1] [error] Illegal value for `line`: Error: Illegal value for `line`
	at t._lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:364:537)
	at Object.lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:363:320)
	at BlockHL.findBot (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:109:36)
	at BlockHL.updateLine (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:45:32)
	at BHLController._onLineChange (C:\Users\jason\.vscode\extensions\byi8220.indented-block-highlighting-1.0.7\out\extension.js:246:23)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:133)
	at e.$acceptEditorPropertiesChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:678)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:744)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:322)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:155)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-10 13:16:59.020] [renderer1] [info] no standard startup: not a new window
[2019-03-10 13:17:47.656] [renderer1] [info] no standard startup: not a new window



</details>

I see that it was trying to use the typescript version bundled with vscode (3.3.1) so I changed all my node_module typescript versions to that, but same problem.

At the top of that output, I do see an error that may be the cause.....

**Comment by jasonswearingen** [comment]
my workaround, for anyone else who wants to lint your project using vscode while this bug is getting fixed.

This hybrid workflow is a little unwieldy, but pretty fast if you set/memorize the proper keyboard shortcuts.


1) add to ```tasks.json```:
```json
		{
			"label": "tslint",
			"type": "shell",
			"command": "tslint --project tsconfig.json --config tslint.json --format verbose",
			"group": {
				"kind": "test",
				"isDefault": true
			}
		},
```
2) run task. The above task is setup as the default test task, so I can run it via ```ctrl alt t``` keyboard shortcut

3) the task outputs tslint errors to the console.  scan it visually.   for a given file with tslint errors, open it via ```ctrl p```

4) the tslint vscode plugin will now lint the opened file, and output errors to the ```Problems``` panel.  press ```F8``` to jump to the first defect.   ```ctrl .``` brings up contextual source actions (auto fix, ignore, etc)

**Comment by mjbvz** [comment]
Not specific to this extension, see: https://github.com/Microsoft/vscode/issues/13953

Tasks are the best approach today
